### ISSUE TITLE
Waiting for .plug.kak.lock

### ISSUE THREAD

**Issue by basbebe** [robertmeta/plug.kak#16]
I regularly have `[…]: Waiting for .plug.kak.lock` next to my topmost plugin in the plugin list (e.g. when I `plug-update`.
What does this mean and do I need to do something about it?
I always get the feeling that the topmost plugin then needs to mbe removed and reinstalled to update.

**Comment by jdugan6240** [comment]
Sorry for the wait. I'm not the maintainer of this plugin, but I do have some ideas.

If I recall correctly, the reason that the .plug.kak.lock file is used is to inform plug.kak that an operation is underway, and this file is removed once the operation is finished. This allows for asynchronous operation of various commands in the background while still preventing execution of operations while another one is still underway.

I think the problem you're having is a similar one to one I had for a while, which is that you may have quit Kakoune while plug.kak was performing an update or some other operation, and this file didn't get cleared. Try navigating to your ~/.config/kak/plugins directory (or wherever your plugins are located) and running rm -f .plug.kak.lock, and then restarting Kakoune to see if that fixes things.

**Comment by basbebe** [comment]
I think that solved it, thanks!
