### ISSUE TITLE
Plug-clean erases plug.kak directory

### ISSUE THREAD

**Issue by jdugan6240** [robertmeta/plug.kak#5]
When you place the following in your kakrc:
`plug 'robertmeta/plug.kak'`
and then restart the kakoune session, and then execute `:plug-clean<ret>`, along with any unmanaged plugins, the plug.kak directory gets deleted as well.

I believe this is because plug.kak doesn't add itself to the `plug_plugins` string, so when the `plug-clean` command compares the repositories in the plugin directory to the list of managed plugins, the plug.kak directory isn't skipped. This indicates that the problem may be with the `plug` command, and not the `plug-clean` command.

**Comment by jdugan6240** [comment]
One workaround that I'm using for right now is to add the following to my kakrc:
`set-option -add global plug_plugins 'robertmeta/plug.kak '`
(the space at the end is intentional, since otherwise the shell won't be able to keep it apart from the next plugin registered with the `plug` command)

This allows all the plug-* commands to recognize plug.kak as a managed plugin. I don't like this, though, since changing hidden options breaks the encapsulation that hidden options provide, and may stop working if plug.kak's implementation changes.

**Comment by Anomalocaridid** [comment]
When I run `plug-clean` on my Kakoune setup, it keeps the plug.kak directory. Have you tried `plug "robertmeta/plug.kak" noload`?

**Comment by jdugan6240** [comment]
Yep, that did it. Thanks!
