### ISSUE TITLE
How do I see the ouput of an install error ?

### ISSUE THREAD

**Issue by sucrecacao** [robertmeta/plug.kak#8]
I got the follow message when trying to update a plugin:
`alexherbo2/snippets.kak: Update Error (128)`
or 
`alexherbo2/auto-pairs.kak: Update Error (1)`

How do I know the meaning of the error code and how can I debug it ?

**Comment by caksoylar** [comment]
`L` (in the `*plug*` window, over the plugin line) shows you the stdout of the update attempt, so I believe there should be useful information there.

**Comment by sucrecacao** [comment]
Yes that help, I could have took a better look
